### ISSUE TITLE
Introduce flows tied to Tendrl objects

### ISSUE THREAD

**Issue by nnDarshan** [Tendrl/ceph_integration#60] opened 2016-12-13 08:54 UTC
All the actions that are specific to an object should be defined as flows under that particular object. Currently such flows are defined at global level. For example, the delete pool flow should be under pool object.
Specification PR: Tendrl/specifications#10
Specification issue: Tendrl/specifications#34

**Comment by shtripat** [comment] 2016-12-30 09:12
Closing as its duplicate of https://github.com/Tendrl/ceph_integration/issues/66

**Closed as completed by shtripat** 2016-12-30 09:12 UTC
